#version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: elibrary-mysql
    restart: always
    environment:
      MYSQL_DATABASE: "elibrary"
      MYSQL_ROOT_PASSWORD: "Som1234567"
    ports:
      # CHANGED: Map host port 3307 to container port 3306 to bypass your other app
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - elibrary-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSom1234567"]
      interval: 10s
      timeout: 5s
      retries: 5

  web-app:
    image: somnath020/my-app:latest
    container_name: my-running-app
    restart: always
    ports:
      - "8087:8087"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - elibrary-network
    entrypoint: ["sh", "-c", "sleep 15 && java -jar app.jar"]
    environment:
      SERVER_PORT: 8087
      MYSQL_HOST: mysqldb
      # Note: web-app still targets internal port 3306 because it's inside the Docker network layout!
      MYSQL_DATABASE: elibrary
      MYSQL_USER: root
      MYSQL_PASSWORD: Som1234567

volumes:
  mysql-data:

networks:
  elibrary-network:
    driver: bridge
