version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: elibrary-mysql
    restart: always
    environment:
      MYSQL_DATABASE: "elibrary"
      MYSQL_ROOT_PASSWORD: "Som1234567"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web-app:
    image: somnath020/my-app:latest
    container_name: my-running-app
    restart: always
    ports:
      - "8087:8087"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SERVER_PORT: 8087
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: elibrary
      MYSQL_USER: root
      MYSQL_PASSWORD: Som1234567

volumes:
  mysql-data:
